const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let activeSession=null,guideIndex=0,guidePhase='work',guideSet=1,guideTotal=1,secondsLeft=0,timerId=null,advanceExercise=false,workStarted=false;
function withWarmup(s){return {...s,minutes:s.minutes+10,items:[['Riscaldamento generale','10 minuti','Corpo libero'],...s.items]}}
function allSessions(){return KPS_PROGRAM.flatMap(w=>w.sessions.map(s=>withWarmup({...s,week:w.week,focus:w.focus})))}
function dots(groups){const pos={shoulders:[[20.7,25.5],[41.1,25.5],[58.4,25.5],[79.6,25.5]],chest:[[26.5,30.5],[35.5,30.5]],back:[[69.1,33.5]],arms:[[19.2,37],[42.6,37],[57.1,37],[81.1,37]],core:[[31,39.5]],glutes:[[64.3,48.5],[73.9,48.5]],quads:[[26.5,57.5],[35.5,57.5]],hamstrings:[[64.3,59],[73.9,59]]};return groups.flatMap(g=>(pos[g]||[]).map((p,i)=>`<i class="muscle-shape ${g} part-${i}" style="left:${p[0]}%;top:${p[1]}%"></i>`)).join('')}
function muscleAvatar(groups){const labels={shoulders:'spalle',chest:'petto',back:'dorso',arms:'braccia e presa',core:'core',glutes:'glutei',quads:'quadricipiti',hamstrings:'posteriori della coscia'},assets={chest:'anatomy-chest.png',shoulders:'anatomy-shoulders.png'},primary=groups.find(g=>assets[g]),src=primary?assets[primary]:'anatomy-avatar.png',overlays=groups.filter(g=>g!==primary);return `<div class="anatomy realistic"><div class="figure"><img src="${src}" alt="Avatar anatomico fronte e retro">${dots(overlays)}</div><div><b>${groups.length?'Muscoli principali':'Coinvolgimento generale'}</b><small>${groups.length?groups.map(x=>labels[x]).join(' · '):'Nessuna singola zona evidenziata'}</small></div></div>`}
function fullDescription(info){return `<b>Obiettivo</b><br>${info.desc}<br><br><b>Esecuzione</b><br>${info.script}<br><br><b>Indicazioni</b><br>Usa un carico che ti permetta di mantenere traiettoria, respirazione e controllo per tutte le ripetizioni. Interrompi la serie se la tecnica cambia o compare dolore.`}
function openSession(code){activeSession=allSessions().find(x=>x.code===code);if(!activeSession)return;$('#sheetTitle').textContent=`${activeSession.code} · ${activeSession.title}`;$('#sheetMeta').textContent=`Settimana ${activeSession.week} · circa ${activeSession.minutes} minuti, incluso warm-up`;$('#sheetItems').innerHTML=activeSession.items.map((x,i)=>{const n=exerciseInfo(x[0]);return `<li><span>${i+1}</span><div><b>${x[0]}</b><small>${x[1]} · ${x[2]}</small><small class="recovery">Recupero: ${n.rest}</small></div><button class="details" onclick="this.nextElementSibling.hidden=!this.nextElementSibling.hidden">Descrizione ↓</button><div class="videoBox" hidden>${muscleAvatar(n.muscles)}<em>DESCRIZIONE</em><p class="video-description">${fullDescription(n)}</p></div></li>`}).join('');$('#sheet').classList.add('open')}
function renderProgram(){const weeks=KPS_PROGRAM.map(w=>`<section class="week"><div class="weekhead"><b>Settimana ${w.week}</b><small>${w.focus}</small></div>${w.sessions.map(s=>`<button onclick="openSession('${s.code}')"><span>${s.code}</span><div><b>${s.title}</b><small>${s.minutes+10} min · warm-up incluso</small></div><i>›</i></button>`).join('')}</section>`).join('');$('#programList').innerHTML=`<button class="catalogHero catalogToggle" onclick="toggleStart()"><span class="pill">PROGRAMMA ATTIVO</span><h2>KPS Start <b id="startToggle">+</b></h2><p>6 settimane · 18 sessioni · principianti</p><small>Apri le settimane e gli allenamenti</small></button><div id="startWeeks" hidden>${weeks}</div><div class="section"><h3>Altri programmi</h3></div>${programCards()}`}
function toggleStart(){const e=$('#startWeeks'),open=e.hidden;e.hidden=!open;$('#startToggle').textContent=open?'−':'+'}
function programCards(){return `<div class="programGrid"><article class="programCard strength" onclick="openPurchase('KPS Strength','79')"><span>INTERMEDIO</span><h3>KPS Strength</h3><p>8 settimane · forza e controllo</p><div class="cardBuy"><b>€79</b><button>Scopri</button></div></article><article class="programCard conditioning" onclick="openPurchase('KPS Conditioning','59')"><span>TUTTI I LIVELLI</span><h3>KPS Conditioning</h3><p>6 settimane · capacità e potenza</p><div class="cardBuy"><b>€59</b><button>Scopri</button></div></article><article class="programCard double" onclick="openPurchase('KPS Double','89')"><span>INTERMEDIO</span><h3>KPS Double</h3><p>8 settimane · due kettlebell</p><div class="cardBuy"><b>€89</b><button>Scopri</button></div></article><article class="programCard performance" onclick="openPurchase('KPS Performance','99')"><span>AVANZATO</span><h3>KPS Performance</h3><p>8 settimane · doppio kettlebell e snatch</p><div class="cardBuy"><b>€99</b><button>Scopri</button></div></article><article class="programCard mobility" onclick="openPurchase('KPS Mobility & Core','39')"><span>COMPLEMENTARE</span><h3>KPS Mobility & Core</h3><p>4 settimane · mobilità e stabilità</p><div class="cardBuy"><b>€39</b><button>Scopri</button></div></article></div>`}
function openPurchase(name,price){$('#buyTitle').textContent=name;$('#singleName').textContent=name;$('#singlePrice').textContent=`€${price}`;$('#checkoutPrice').textContent=`€${price}`;$('#buySingle').dataset.price=price;$('#purchase').classList.add('open');selectOffer('single')}
function selectOffer(type){const single=type==='single';$('#buySingle').classList.toggle('selected',single);$('#buyMember').classList.toggle('selected',!single);$('#checkoutPrice').textContent=single?`€${$('#buySingle').dataset.price}`:'€19,90/mese';$('#checkoutNote').textContent=single?'Pagamento unico · accesso permanente':'Rinnovo mensile · annullabile in qualsiasi momento'}
function closePurchase(){$('#purchase').classList.remove('open')}
function showView(id){$$('.view').forEach(v=>v.hidden=true);$('#'+id).hidden=false;$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo(0,0)}
function restSeconds(text){const m=text.match(/(\d+)(?:–(\d+))?\s*s/);return m?Number(m[2]||m[1]):text==='Nessuno'?0:60}
function timedSeconds(text){const s=text.match(/(\d+)(?:–\d+)?\s*s(?:econdi)?/i),m=text.match(/(\d+)\s*min/i);return s?Number(s[1]):m?Number(m[1])*60:0}
function setCount(text){const x=text.match(/^(\d+)\s*[×x]/i),g=text.match(/(\d+)\s*giri/i),r=text.match(/(\d+)\s*round/i);return Number(x?.[1]||g?.[1]||r?.[1]||1)}
function repTarget(text){const x=text.match(/^\d+\s*[×x]\s*([^·]+)/i);return x?x[1].trim():text}
function formatTime(n){return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function currentItem(){return activeSession.items[guideIndex]}
function prepareWork(){guidePhase='work';workStarted=false;guideTotal=setCount(currentItem()[1]);secondsLeft=timedSeconds(currentItem()[1]);renderGuide()}
function renderGuide(){const item=currentItem(),info=exerciseInfo(item[0]),timed=timedSeconds(item[1])>0;$('#guideStep').textContent=`Esercizio ${guideIndex+1}/${activeSession.items.length}`;$('#guideStatus').textContent=guidePhase==='rest'?'RECUPERO':item[0]==='Riscaldamento generale'?'WARM-UP':'LAVORO';$('#guideStatus').className=`guideStatus ${guidePhase}`;$('#guideName').textContent=guidePhase==='rest'?'Recupero':item[0];$('#guidePrescription').textContent=guidePhase==='rest'?(advanceExercise?(guideIndex<activeSession.items.length-1?`Prossimo esercizio: ${activeSession.items[guideIndex+1][0]}`:'Ultimo recupero'):`Prossima: serie ${guideSet+1} di ${guideTotal}`):`Serie ${guideSet} di ${guideTotal} · Carico ${item[2]}`;$('#guideDescription').innerHTML=guidePhase==='rest'?'Respira, sciogli la presa e prepara la posizione per la prossima serie.':fullDescription(info);$('#guideMedia').innerHTML=guidePhase==='rest'?'<div class="restVisual">RECUPERO</div>':'<div class="mediaPlaceholder"><span>▶</span><b>Dimostrazione in loop</b><small>Il tuo MP4 verrà mostrato qui</small></div>';$('#guideTimer').innerHTML=guidePhase==='rest'?formatTime(secondsLeft):(timed?formatTime(secondsLeft):`<strong>${repTarget(item[1])}</strong><small>RIPETIZIONI</small>`);$('#guidePrimary').textContent=guidePhase==='rest'?'Salta recupero':timed?(workStarted?'Pausa timer':'Avvia timer'):'Ho completato la serie';const done=guideIndex+(guideSet-1)/Math.max(guideTotal,1);$('#guideBar').style.width=`${done/activeSession.items.length*100}%`}
function tick(){clearInterval(timerId);timerId=setInterval(()=>{if(secondsLeft>0){secondsLeft--;$('#guideTimer').textContent=formatTime(secondsLeft)}else{clearInterval(timerId);if(guidePhase==='rest')finishRest();else completeWorkSet()}},1000)}
function startGuided(){if(!activeSession)return;guideIndex=0;guideSet=1;$('#sheet').classList.remove('open');$('#coach').classList.add('open');prepareWork()}
function primaryGuide(){if(guidePhase==='rest'){finishRest();return}if(timedSeconds(currentItem()[1])){if(!workStarted){workStarted=true;renderGuide();tick()}else{workStarted=false;clearInterval(timerId);renderGuide()}return}completeWorkSet()}
function completeWorkSet(){advanceExercise=guideSet>=guideTotal;guidePhase='rest';workStarted=false;secondsLeft=restSeconds(exerciseInfo(currentItem()[0]).rest);if(!secondsLeft){finishRest();return}renderGuide();tick()}
function finishRest(){clearInterval(timerId);if(advanceExercise){if(guideIndex>=activeSession.items.length-1){completeGuide();return}guideIndex++;guideSet=1}else guideSet++;prepareWork()}
function completeGuide(){guidePhase='done';$('#guideName').textContent='Sessione completata';$('#guidePrescription').textContent='Tutte le serie sono state completate.';$('#guideMedia').innerHTML='<div class="restVisual">✓</div>';$('#guideTimer').textContent='FINE';$('#guideDescription').textContent='Ottimo lavoro. Registra la percezione dello sforzo e le eventuali note tecniche.';$('#guideBar').style.width='100%'}
function nextGuide(){clearInterval(timerId);if(guideIndex>=activeSession.items.length-1){completeGuide();return}guideIndex++;guideSet=1;prepareWork()}
function prevGuide(){clearInterval(timerId);guideIndex=Math.max(0,guideIndex-1);guideSet=1;prepareWork()}
function closeGuide(){clearInterval(timerId);$('#coach').classList.remove('open')}
document.addEventListener('DOMContentLoaded',()=>{renderProgram();$$('#home .workout .icon').forEach((e,i)=>e.textContent=['A','B','C'][i]);const anchor=$('#homeStartWeeks'),heading=document.createElement('div'),hp=document.createElement('div');heading.className='section';heading.innerHTML='<h3>Esplora KPS</h3><span class="link">Programmi</span>';hp.id='homePrograms';hp.innerHTML=programCards();anchor.after(heading,hp);$$('[data-session]').forEach(e=>e.onclick=()=>openSession(e.dataset.session));$$('nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#closeSheet').onclick=()=>$('#sheet').classList.remove('open');$('#startSession').onclick=startGuided;$('#guidePrimary').onclick=primaryGuide;$('#guideNext').onclick=nextGuide;$('#guidePrev').onclick=prevGuide;$('#closeGuide').onclick=closeGuide;$('#closePurchase').onclick=closePurchase;$('#buySingle').onclick=()=>selectOffer('single');$('#buyMember').onclick=()=>selectOffer('member')});
